- name: Configure web server
  hosts: web            # hosts from inventory.ini
  become: true          # use sudo

  roles:
    - nginx             # nginx role - which execute from C:\Users\Filip\azure-devops-infra\ansible\roles\nginx\tasks\main.yml

